### ISSUE TITLE
Not a git repository: '.git'

### ISSUE THREAD

**Issue by davidmatas** [nlf/precommit-hook#52] opened 2015-03-30 22:20 UTC
Hi, I'm getting this:

```
Fatal: Not a git repository: '.git'
no checks for pre-commit found.. skipping
running csslint...failed!
Running "csslint:git" (csslint) task
```

Not sure if should I worry about `Fatal: Not a git repository: '.git'`, what could be the problem?

**Comment by nlf** [comment] 2015-03-30 22:22
What does your project's directory layout look like? How did you install `precommit-hook`? When you get that error, is it while trying to commit? Also, can you share your `package.json` (or at least the `scripts` and `pre-commit` sections)

**Comment by davidmatas** [comment] 2015-03-31 07:51
I installed with `npm install precommit-hook --save-dev` and yes, I get that when I commit. My project layouts is typical I think:

```
/root_folder
    |
    |_ /node_modules
    |
    |_ /scripts
    |     |_ csslint.sh
    |
    |_ package.json
```

My package.json:

```
"devDependencies": {
   ...
    "precommit-hook": "~2.0.1"
},
"scripts": {
    "pretest": "./scripts/pretest.sh",
    "test": "./scripts/test.sh",
    "doc": "./scripts/doc.sh",
    "csslint": "./scripts/csslint.sh"
},
"pre-commit": ["csslint"]
```

**Comment by davidmatas** [comment] 2015-03-31 08:32
I've found what the problem, I also have this in the layout:

```
/root_folder
    |
    |_ /lib
          |_ i18n
                |_ package.json
```

**Comment by nlf** [comment] 2015-04-01 21:35
I'm not sure I follow.. having that in your layout shouldn't cause the not a git repository error. I'll see if I can reproduce here.

**Comment by davidmatas** [comment] 2015-04-01 22:09
I think yes because `i18n` contains a `package.json` but doesn't contain a git repository

**Comment by hrgui** [comment] 2015-04-02 21:09
I also have a similar issue, but I think it's because of the bower_components folder that I have which contains package.json files. 
````
no checks for pre-commit found.. skipping
fatal: Not a git repository: '.git'
no checks for pre-commit found.. skipping
fatal: Not a git repository: '.git'
no checks for pre-commit found.. skipping
````

My tree structure is like this:
project_folder
 - bower_components
 - node-modules
 - js
 - css
 - package.json

**Comment by nlf** [comment] 2015-04-02 21:09
thanks for the additional info, i'll hopefully have this fixed soon

**Comment by nlf** [comment] 2015-04-28 00:35
can you update your node modules, and make sure that `npm ls git-validate` reports version 1.1.2 and let me know if you still see this error?

**Comment by pselden** [comment] 2015-04-29 14:09
Appears to be working for me now after updating git-validate. Thank you.

**Comment by hrgui** [comment] 2015-04-29 14:27
Working for me as well after updating git-validate.

**Comment by davidmatas** [comment] 2015-05-05 14:43
Working :)

**Comment by nlf** [comment] 2015-05-07 16:17
Closing this as resolved, thanks for testing

**Closed by nlf** 2015-05-07 16:17 UTC
Labels: question
